---
- name: Deploy Secondary MariaDB Server in Docker for Replication
  hosts: all
  become: true
  vars:
    mariadb_version: "10.1.48"  # Replace with your desired version
    mariadb_primary_host: "172.18.0.228"  # Replace with the IP of the primary server
    mariadb_replication_user: "replicator"
    mariadb_replication_password: "replicator_password"  # Replace with your replication user password
    mariadb_container_name: "mariadb_secondary"
    mariadb_root_password: "your_strong_root_password"  # Replace with your desired password
    mariadb_database: "exampledb"

  tasks:
    - name: Pull MariaDB Docker image
      community.docker.docker_image:
        name: "mariadb:{{ mariadb_version }}"
        source: pull

    - name: Run Secondary MariaDB container
      community.docker.docker_container:
        name: "{{ mariadb_container_name }}"
        image: "mariadb:{{ mariadb_version }}"
        state: started
        restart_policy: always
        published_ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
          MYSQL_DATABASE: "{{ mariadb_database }}"
        command: >
          --server-id=2
          --replicate-do-db=exampledb

    - name: Wait for MariaDB to start
      community.docker.docker_container_info:
        name: "{{ mariadb_container_name }}"
      register: mariadb_container_info
      until: mariadb_container_info.container.State.Running
      retries: 10
      delay: 10

    
    - name: Configure replication on Secondary server
      community.mysql.mysql_replication:
        mode: changeprimary
        master_host: "{{ mariadb_primary_host }}"
        master_user: "{{ mariadb_replication_user }}"
        master_password: "{{ mariadb_replication_password }}"
        master_log_file: "mysql-bin.000005"  # Replace with current log file of the primary
        master_log_pos: 659  # Replace with the current log position of the primary
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_host: "{{ ansible_host }}"
