version: '3.1'

services: 
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - 3306:3306
    network_mode: bridge
